"use client";import{useEffect,useState}from"react";
export default function Home(){const[d,setD]=useState<any>();const[err,setErr]=useState("");async function load(){try{setErr("");const r=await fetch("/api/optimise",{cache:"no-store"});const j=await r.json();if(!r.ok)throw Error(j.error||"Unable to load");setD(j)}catch(e){setErr(String(e))}}useEffect(()=>{load()},[]);
if(err)return <main className="shell"><h1>FPL Optimiser</h1><div className="card">{err}</div></main>;
if(!d)return <main className="shell"><h1>FPL Optimiser</h1><p className="muted">Loading live FPL data…</p></main>;
const r=d.result;return <main className="shell"><header className="top"><div><div className="eyebrow">FPL Optimiser V0.3</div><h1 className="title">Your live decision engine</h1><p className="sub">GW {d.gw} • {d.team?.name||"Your team"} • five-GW projection horizon</p></div><button className="btn" onClick={load}>Refresh</button></header>
<div><span className="pill">LIVE FPL ✓</span><span className="pill">15-player squad ✓</span><span className="pill">Fixture model ✓</span><span className="pill">Transfer engine ✓</span></div>
<section className="grid"><div className="card"><h2>Current squad</h2><table className="table"><thead><tr><th>Player</th><th>Pos</th><th>Price</th><th>Proj.</th><th>Start</th></tr></thead><tbody>{r.current.map((x:any)=><tr key={x.player.id}><td>{x.player.name}</td><td>{x.player.position}</td><td>£{x.player.price.toFixed(1)}m</td><td className="good">{x.player.projected}</td><td>{x.player.startProbability}%</td></tr>)}</tbody></table></div>
<div className="card"><h2>Suggested transfers</h2>{r.transferIdeas.map((x:any,i:number)=><div className="transfer" key={i}><div><b>{x.in}</b> <span className="muted">for {x.out}</span><br/><span className="muted">£{x.price.toFixed(1)}m • projected gain</span></div><span className="badge">+{x.delta}</span></div>)}</div></section>
<section className="card" style={{marginTop:14}}><h2>Projected XI</h2><p className="hero">{r.starters.slice(0,11).map((x:any)=>x.player.name).join(" • ")}</p><p className="muted">Captaincy/chip optimisation is the next layer; this version is deliberately showing the underlying projection and transfer signals rather than pretending the current heuristic is a full solver.</p></section>
<section className="card" style={{marginTop:14}}><h2>What I'm building next</h2><p className="muted">Transfer affordability and team constraints → free-transfer roll strategy → hits → captain/vice → BB/TC/FH/WC → fixture-aware multi-GW search → risk/aggression controls → backtesting.</p></section></main>}