"use client";import{useEffect,useState}from"react";
export default function Home(){const[d,setD]=useState<any>();const[err,setErr]=useState("");async function load(){try{setErr("");const r=await fetch("/api/optimise",{cache:"no-store"});const j=await r.json();if(!r.ok)throw Error(j.error||"Unable to load");setD(j)}catch(e){setErr(String(e))}}useEffect(()=>{load()},[]);
if(err)return <main className="shell"><h1>FPL Optimiser</h1><div className="card">{err}</div></main>;
if(!d)return <main className="shell"><h1>FPL Optimiser</h1><p className="muted">Loading live FPL data…</p></main>;
const r=d.result;return <main className="shell"><header className="top"><div><div className="eyebrow">FPL Optimiser V0.7</div><h1 className="title">Your live decision engine</h1><p className="sub">GW {d.gw} • {d.team?.name||"Your team"} • 7-GW decision horizon</p></div><button className="btn" onClick={load}>Refresh</button></header>
<div><span className="pill">LIVE FPL ✓</span><span className="pill">{r.freeTransfers} FT</span><span className="pill">Bank £{r.bank.toFixed(1)}m</span><span className="pill">15-player squad ✓</span><span className="pill">Formation rules ✓</span><span className="pill">Budget rules ✓</span><span className="pill">Chip planner ✓</span><span className="pill">Selling value ✓</span></div>
<section className="grid"><div className="card"><h2>Current squad</h2><table className="table"><thead><tr><th>Player</th><th>Pos</th><th>Price</th><th>Proj.</th><th>Play</th></tr></thead><tbody>{r.current.map((x:any)=><tr key={x.player.id}><td>{x.player.name}</td><td>{({1:"GK",2:"DEF",3:"MID",4:"FWD"} as any)[x.player.position]}</td><td>£{x.player.price.toFixed(1)}m</td><td className="good">{x.player.projected}</td><td>{x.player.startProbability}%</td></tr>)}</tbody></table></div>
<div className="card"><h2>Suggested transfers</h2>{r.transferIdeas.length?r.transferIdeas.map((x:any,i:number)=><div className="transfer" key={i}><div><b>{x.in}</b> <span className="muted">for {x.out}</span><br/><span className="muted">{x.position} • £{x.price.toFixed(1)}m • projected gain</span></div><span className="badge">+{x.delta}</span></div>):<p className="muted">No affordable positive-value transfers found within FPL squad rules.</p>}</div></section>
<section className="grid" style={{marginTop:14}}><div className="card"><h2>Projected XI</h2><p className="hero">{r.starters.map((x:any)=>x.player.name).join(" • ")}</p><p className="muted">Formation-valid XI using 1 GK, 3–5 defenders, 2–5 midfielders and 1–3 forwards.</p></div>
<div className="card"><h2>Chip suggestions</h2>{r.chips.suggestions.map((x:any,i:number)=><div className="transfer" key={i}><div><b>{x.chip}</b><br/><span className="muted">{x.reason}</span></div></div>)}</div></section>
<section className="card" style={{marginTop:14}}><h2>6-gameweek decision plan</h2>{r.decisionPlan.map((x:any)=><div className="transfer" key={x.gw}><div><b>GW {x.gw}</b><br/><span className="muted">{x.action||"Hold transfer"}{x.chip?` • ${x.chip}`:""} • Captain: {x.cap?.captain?.name||"—"} • {x.formation}</span></div><span className="badge">{x.ft} FT</span></div>)}</section><section className="card" style={{marginTop:14}}><h2>FPL rules applied</h2><p className="muted">15-player squad • max 3 players from one club • position-locked transfers • budget/Bank constraint • valid formation • chips assessed against future fixture conditions.</p></section></main>}