"use client";import{useEffect,useState}from"react";
export default function Home(){const[d,setD]=useState<any>();const[err,setErr]=useState("");const[loading,setLoading]=useState(true);const[lastRun,setLastRun]=useState("");async function load(){try{setLoading(true);setErr("");const r=await fetch("/api/optimise",{cache:"no-store"});const j=await r.json();if(!r.ok)throw Error(j.error||"Unable to load");setD(j);setLastRun(new Date().toLocaleString())}catch(e){setErr(String(e))}finally{setLoading(false)}}useEffect(()=>{load()},[]);
if(err)return <main className="shell"><h1>FPL Optimiser</h1><div className="card">{err}</div></main>;
if(!d)return <main className="shell"><h1>FPL Optimiser</h1><p className="muted">Loading live FPL data…</p></main>;
const r=d.result;const formationLabel=(f:string)=>f?.replace(/^1-/ ,"")||"—";const chipLabel=(c:string)=>({wildcard:"Wildcard",freehit:"Free Hit",bboost:"Bench Boost","3xc":"Triple Captain"} as any)[c]||c;const ftLabel=(n:number)=>String(n)+" Free Transfer"+(n===1?"":"s");return <main className="shell"><header className="top"><div><div className="eyebrow">FPL Optimiser V0.9</div><h1 className="title">Your live decision engine</h1><p className="sub">Gameweek {d.gw} • {d.team?.name||"Your team"} • 7-gameweek decision horizon</p></div><div style={{display:"flex",gap:8,alignItems:"center"}}><button className="btn" onClick={load} disabled={loading}>{loading?"Optimising…":"🧠 Run Optimiser"}</button><button className="btn" onClick={load} disabled={loading}>{loading?"":"↻ Refresh live data"}</button></div></header>
<div><span className="pill">Live FPL data ✓</span><span className="pill">Historical model ✓</span><span className="pill">5 seasons trained</span><span className="pill">{ftLabel(r.freeTransfers)}</span><span className="pill">Bank £{r.bank.toFixed(1)}m</span><span className="pill">15-player squad ✓</span><span className="pill">Formation rules ✓</span><span className="pill">Budget rules ✓</span><span className="pill">Chip planner ✓</span><span className="pill">Selling value ✓</span></div>
<section className="card" style={{marginTop:14}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><h2 style={{marginBottom:4}}>Optimiser status</h2><p className="muted">Live FPL data • 5-season trained historical model • 7-gameweek horizon</p></div><span className="badge">Last run: {lastRun||"—"}</span></div></section>
<section className="grid"><div className="card"><h2>Current squad</h2><table className="table"><thead><tr><th>Player</th><th>Position</th><th>Price</th><th>Projected points</th><th>Play chance</th></tr></thead><tbody>{r.current.map((x:any)=><tr key={x.player.id}><td>{x.player.name}</td><td>{({1:"Goalkeeper",2:"Defender",3:"Midfielder",4:"Forward"} as any)[x.player.position]}</td><td>£{x.player.price.toFixed(1)}m</td><td className="good">{x.player.projected}</td><td>{x.player.startProbability}%</td></tr>)}</tbody></table></div>
<div className="card"><h2>Suggested transfers</h2><p className="muted">Based on your live FPL squad, bank, free transfers, trained historical model and current rules.</p>{r.transferIdeas.length?r.transferIdeas.map((x:any,i:number)=><div className="transfer" key={i}><div><b>{x.in}</b> <span className="muted">for {x.out}</span><br/><span className="muted">{x.position} • £{x.price.toFixed(1)}m • projected gain</span></div><span className="badge">+{x.delta} pts</span></div>):<p className="muted">No affordable positive-value transfers found within FPL squad rules.</p>}</div></section>
<section className="card" style={{marginTop:14}}><h2>Recommended substitutions</h2>{r.substitutionPlan?.length?r.substitutionPlan.map((x:any,i:number)=><div className="transfer" key={i}><div><b>Start {x.bench}</b> <span className="muted">instead of {x.starter}</span><br/><span className="muted">{x.reason} Projected: {x.benchProjected} vs {x.starterProjected} • Start chance: {x.benchStart}% vs {x.starterStart}%</span></div><span className="badge">+{x.gain}</span></div>):<p className="muted">No substitution recommended — the current starting XI is the highest-value combination under the model.</p>}</section><section className="grid" style={{marginTop:14}}><div className="card"><h2>Projected starting XI</h2><p className="muted"><b>Your live FPL XI:</b> {r.currentStartingXI?.join(" • ")||"—"}<br/><b>Live bench:</b> {r.currentBench?.join(" • ")||"—"}</p><p className="hero">{r.starters.map((x:any)=>x.player.name).join(" • ")}</p><p className="muted"><b>Formation: {formationLabel(r.projectedGameweek?.formation)}</b><br/>1 goalkeeper • {formationLabel(r.projectedGameweek?.formation).split("-")[0]} defenders • {formationLabel(r.projectedGameweek?.formation).split("-")[1]} midfielders • {formationLabel(r.projectedGameweek?.formation).split("-")[2]} forwards</p></div>
<div className="card"><h2>Chip suggestions</h2>{r.chips.suggestions.map((x:any,i:number)=><div className="transfer" key={i}><div><b>{chipLabel(x.chip)}</b><br/><span className="muted">{x.reason}</span></div></div>)}</div></section>
<section className="card" style={{marginTop:14}}><h2>7-gameweek decision plan</h2>{r.decisionPlan.map((x:any)=><div className="transfer" key={x.gw}><div><b>Gameweek {x.gw}</b><br/><span className="muted">{x.action||"Hold transfer"}{x.chip?" • "+chipLabel(x.chip):""} • Captain: {x.cap?.captain?.name||"—"} • Formation: {formationLabel(x.formation)}</span></div><span className="badge">{ftLabel(x.ft)}</span></div>)}</section><section className="card" style={{marginTop:14}}><h2>FPL rules applied</h2><p className="muted">15-player squad • maximum 3 players from one club • position structure and budget constraints • budget and Bank constraint • valid formation • chips assessed against future fixture conditions.</p></section></main>}