// Generated by scripts/historical-training.mjs.
// Historical weights are priors only; live FPL rules are enforced separately in lib/engine.ts.
export const HISTORICAL_MODEL={
  trainedSeasons:["2021-22","2022-23","2023-24","2024-25","2025-26"],
  weights:{form3:.16,form5:.10,p90:.15,xgi90:.18,xg90:.05,xa90:.05,dc90:.07,startRate:.10,minutesRate:.14,bias:0},
  learning:"walk-forward online learning; no future GW data is exposed to the decision step",
  liveRules:{maxFreeTransfers:5,chipSets:2,chipSplitGameweek:20,oneChipPerGameweek:true,freeHitConsecutive:false}
} as const;
