// Generated by scripts/historical-training.mjs.
// Walk-forward historical learning only; live rules remain enforced separately.
export const HISTORICAL_MODEL={
  "trainedSeasons": [
    "2021-22",
    "2022-23",
    "2023-24",
    "2024-25",
    "2025-26"
  ],
  "weights": {
    "form3": 1.4988318435019907,
    "form5": 1.4978177533406822,
    "p90": 1.5,
    "xgi90": 1.4716374173553464,
    "xg90": 1.4792443014353838,
    "xa90": 1.4698294646807002,
    "dc90": 1.5,
    "startRate": 1.4603214356124437,
    "minutesRate": 1.46116223287508,
    "bias": -2.952
  },
  "features": [
    "form3",
    "form5",
    "p90",
    "xgi90",
    "xg90",
    "xa90",
    "dc90",
    "startRate",
    "minutesRate"
  ],
  "liveRules": {
    "maxFreeTransfers": 5,
    "chipSets": 2,
    "chipSplitGameweek": 20,
    "oneChipPerGameweek": true,
    "freeHitConsecutive": false
  }
} as const;
