// Generated by scripts/historical-training.mjs.
// Walk-forward historical learning only; live rules remain enforced separately.
export const HISTORICAL_MODEL={
  "trainedSeasons": [
    "2021-22",
    "2022-23",
    "2023-24",
    "2024-25",
    "2025-26"
  ],
  "weights": {
    "form3": 0.21722813048098807,
    "form5": 0.1594433234497025,
    "p90": 0.14297192154931068,
    "xgi90": 0.18932392206359758,
    "xg90": 0.05787372251738305,
    "xa90": 0.05859200791895121,
    "dc90": 0.07324754781870459,
    "startRate": 0.14337990325277736,
    "minutesRate": 0.20147523392651143,
    "bias": -0.07568677227549812
  },
  "features": [
    "form3",
    "form5",
    "p90",
    "xgi90",
    "xg90",
    "xa90",
    "dc90",
    "startRate",
    "minutesRate"
  ],
  "liveRules": {
    "maxFreeTransfers": 5,
    "chipSets": 2,
    "chipSplitGameweek": 20,
    "oneChipPerGameweek": true,
    "freeHitConsecutive": false
  }
} as const;
